### ISSUE TITLE
[Feature] Refactor the code to make it more maintainable and readable

### ISSUE THREAD

**Issue by ryan4yin** [ryan4yin/nix-config#83]
## Why refactoring is needed?

My nix config was very simple at the beginning, but as I kept updating and adding new things, it became more and more complicated.

The current pain points of this project is:

1. It's **hard to read**.
1. It's **hard to add a new host** into the config, I have to edit several nix file very carefully.
2. Every time I modified some shared configs, I have to deploy and **test** it on all my 20 hosts, which consumes energy and time.
3. It's **hard to refactor** the config, nix's error message is obscure, and my poor project structure made it even worse.

## The goal I want to achieve through refactoring

Sort by priority:

- [x] **Make it simple and easy to add a new host**. #79
- [x] **Make refactoring and code modification more quickly and smoother by**
  - [x] Adding eval tests #88
  - [x] Adding integration tests #93 
- [x] Make it more readable, to myself.(Readability to beginners will not be considered...) #79
